-- DDL

create table users
(
    id           integer generated by default as identity
            primary key,
    first_name   varchar(30),
    last_name    varchar(50),
    phone_number varchar(20)
);

create table record
(
    id           integer generated by default as identity
            primary key,
    first_name   varchar(30),
    last_name    varchar(50),
    phone_number varchar(20),
    owner        integer not null
            references users
);

create unique index record_id_uindex
    on record (id);